treemaker: "python/tensorflow_treemaker_GNN.py"
modelDir: "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/model_checkpoints"
modelName: "particle_net_mod1b_ak8_noSD_2022-06-10_17-14-23"
modelConfig: "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/condor_jobs/training/particle_net_mod1b_ak8_noSD_2022-06-10_17-14-23/test_config_particlenet_debug_3.yml"
modelFiles:
    epoch22: "weights_epoch-22.hdf5"
classifiers:
    lepTop_vs_lepW:     "{node0}/({node0}+{node1})"
    lepTop_vs_lepZ:     "{node0}/({node0}+{node2})"
    lepTop_vs_qcd:      "{node0}/({node0}+{node3})"
samples:
# 2018
    #- "ntupleLists/TTJets_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/TTJets_HT-800to1200_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/TTJets_HT-1200to2500_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/TTJets_HT-2500toInf_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    
    - "ntupleLists/ZprimeToTT_M2000_W20_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    - "ntupleLists/ZprimeToTT_M3000_W30_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    - "ntupleLists/ZprimeToTT_M4000_W40_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    - "ntupleLists/ZprimeToTT_M5000_W50_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    
    - "ntupleLists/Wprimetotb_M3000W30_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2_MINIAODSIM_latest.txt:treeMaker/tree"
    - "ntupleLists/Wprimetotb_M3000W30_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    - "ntupleLists/Wprimetotb_M4000W40_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    - "ntupleLists/Wprimetotb_M4000W40_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    - "ntupleLists/Wprimetotb_M5000W50_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    - "ntupleLists/Wprimetotb_M5000W50_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    - "ntupleLists/Wprimetotb_M6000W60_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    - "ntupleLists/Wprimetotb_M6000W60_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    
    #- "ntupleLists/WJetsToLNu_Pt-400To600_TuneCP5_13TeV-amcatnloFXFX-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/WJetsToLNu_Pt-600ToInf_TuneCP5_13TeV-amcatnloFXFX-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #
    #- "ntupleLists/DYJetsToLL_Pt-400To650_TuneCP5_13TeV-amcatnloFXFX-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/DYJetsToLL_Pt-650ToInf_TuneCP5_13TeV-amcatnloFXFX-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    
    - "ntupleLists/QCD_Pt_300to470_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    - "ntupleLists/QCD_Pt_470to600_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    - "ntupleLists/QCD_Pt_600to800_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    - "ntupleLists/QCD_Pt_800to1000_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    - "ntupleLists/QCD_Pt_1000to1400_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    - "ntupleLists/QCD_Pt_1400to1800_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    - "ntupleLists/QCD_Pt_1800to2400_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    - "ntupleLists/QCD_Pt_2400to3200_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    
    
# 2017
    #- "ntupleLists/ZprimeToTT_M2000_W20_TuneCP2_13TeV-madgraphMLM-pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14_ext1-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/ZprimeToTT_M3000_W30_TuneCP2_13TeV-madgraphMLM-pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14_ext1-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/ZprimeToTT_M4000_W40_TuneCP2_13TeV-madgraphMLM-pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14_ext1-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/ZprimeToTT_M5000_W50_TuneCP2_13TeV-madgraphMLM-pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14_ext1-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/ZprimeToTT_M6000_W60_TuneCP2_13TeV-madgraphMLM-pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14_ext1-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    
    #- "ntupleLists/Wprimetotb_M3000W30_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v2_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/Wprimetotb_M3000W30_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/Wprimetotb_M4000W40_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/Wprimetotb_M4000W40_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/Wprimetotb_M5000W50_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/Wprimetotb_M5000W50_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/Wprimetotb_M6000W60_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/Wprimetotb_M6000W60_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #
    #- "ntupleLists/QCD_Pt_300to470_TuneCP5_13TeV_pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/QCD_Pt_470to600_TuneCP5_13TeV_pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/QCD_Pt_600to800_TuneCP5_13TeV_pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/QCD_Pt_800to1000_TuneCP5_13TeV_pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/QCD_Pt_1000to1400_TuneCP5_13TeV_pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/QCD_Pt_1400to1800_TuneCP5_13TeV_pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/QCD_Pt_1800to2400_TuneCP5_13TeV_pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1_MINIAODSIM_latest.txt:treeMaker/tree"
    #- "ntupleLists/QCD_Pt_2400to3200_TuneCP5_13TeV_pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1_MINIAODSIM_latest.txt:treeMaker/tree"

printEvery: 1000
cpuFrac: 0.99
outputDirBase: "training_results/classifier_trees"
condordir: "training_results/condor_jobs/treemaker"
condorconfig: "configs/condor/condor_config_template_general.submit"
condorscript: "scripts/condor/condor_script_template_general.sh"
outputTag: ""
