
samples:
    
    TTJets:
        names:
            - "TTJets_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
            - "TTJets_HT-800to1200_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
            - "TTJets_HT-1200to2500_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
            - "TTJets_HT-2500toInf_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
        weights:
            - 1.821
            - 0.7532
            - 0.1316
            - 0.001407
    
    Wprimetotb_M3000W30:
        names:
            - "Wprimetotb_M3000W30_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2_MINIAODSIM:latest"
            - "Wprimetotb_M3000W30_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
        weights:
            - 1.0
            - 1.0
    
    Wprimetotb_M4000W40:
        names:
            - "Wprimetotb_M4000W40_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
            - "Wprimetotb_M4000W40_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
        weights:
            - 1.0
            - 1.0
    
    Wprimetotb_M6000W60:
        names:
            - "Wprimetotb_M6000W60_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
            - "Wprimetotb_M6000W60_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
        weights:
            - 1.0
            - 1.0
    
    WJets:
        names:
            - "WJetsToLNu_Pt-400To600_TuneCP5_13TeV-amcatnloFXFX-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
            - "WJetsToLNu_Pt-600ToInf_TuneCP5_13TeV-amcatnloFXFX-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
        weights:
            - 3.604
            - 0.5545
    
    DYJets:
        names:
            - "DYJetsToLL_Pt-400To650_TuneCP5_13TeV-amcatnloFXFX-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
            - "DYJetsToLL_Pt-650ToInf_TuneCP5_13TeV-amcatnloFXFX-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
        weights:
            - 0.5164
            - 0.04796
    

#friendlist:
#    
#    pnet:
#        - 

curves:
    -   label: "t^{lep} (t#bar{t}) vs. W^{lep} (W+jets)"
        sig:
            sample:         "TTJets"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        bkg:
            sample:         "WJets"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenWDR_reco < 0.6) && ({jet}_nearestGenWIsLeptonic_reco > 0.5)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_with-WZ_2022-05-11_18-55-28"
                tag:                null
                #usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:        "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
        classifier:     "epoch11_lepTop_vs_lepW"
        classifiercut:  "{classifier} > {value}"
        color: 2
        linestyle: 1
    
    
    -   label: "t^{lep} (W'_{6 TeV}) vs. W^{lep} (W+jets)"
        sig:
            sample:         "Wprimetotb_M6000W60"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        bkg:
            sample:         "WJets"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenWDR_reco < 0.6) && ({jet}_nearestGenWIsLeptonic_reco > 0.5)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_with-WZ_2022-05-11_18-55-28"
                tag:                null
                #usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:        "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
        classifier:     "epoch11_lepTop_vs_lepW"
        classifiercut:  "{classifier} > {value}"
        color: 2
        linestyle: 7
    
    
    -   label: "t^{lep} (t#bar{t}) vs. Z^{lep} (Z+jets)"
        sig:
            sample:         "TTJets"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        bkg:
            sample:         "DYJets"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenZDR_reco < 0.6) && ({jet}_nearestGenZIsLeptonic_reco > 0.5) && ({jet}_nearestGenZlep1DR_reco < 0.6) && ({jet}_nearestGenZlep2DR_reco < 0.6)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_with-WZ_2022-05-11_18-55-28"
                tag:                null
                #usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:        "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
        classifier:     "epoch11_lepTop_vs_lepZ"
        classifiercut:  "{classifier} > {value}"
        color: 4
        linestyle: 1
    
    
    -   label: "t^{lep} (W'_{6 TeV}) vs. Z^{lep} (Z+jets)"
        sig:
            sample:         "Wprimetotb_M6000W60"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        bkg:
            sample:         "DYJets"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenZDR_reco < 0.6) && ({jet}_nearestGenZIsLeptonic_reco > 0.5) && ({jet}_nearestGenZlep1DR_reco < 0.6) && ({jet}_nearestGenZlep2DR_reco < 0.6)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_with-WZ_2022-05-11_18-55-28"
                tag:                null
                #usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:        "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
        classifier:     "epoch11_lepTop_vs_lepZ"
        classifiercut:  "{classifier} > {value}"
        color: 4
        linestyle: 7
    

xtitle: "Signal efficiency"
ytitle: "Background efficiency"
xrange:
    - 0.0
    - 1.0
yrange:
    - 1.0e-6
    - 1.0
logx: false
logy: true
gridx: true
gridy: true
legendpos: "UL"
legendtextsize: 0.04
cpufrac: 0.9
outtag: "lepTop-vs-lepWZ"
#outfile: "plots/ROCs/particle_net_mod1b_ak8_with-WZ_2022-05-11_18-55-28/ROC.pdf"
outdir: "plots/ROCs/particle_net_mod1b_ak8_with-WZ_2022-05-11_18-55-28/2018"
