
samples:
    
    TTJets:
        names:
            - "TTJets_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-27_15-16-05"
            - "TTJets_HT-800to1200_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-27_15-18-18"
            - "TTJets_HT-1200to2500_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-27_15-19-37"
            - "TTJets_HT-2500toInf_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-27_15-20-01"
        weights:
            - 1.821
            - 0.7532
            - 0.1316
            - 0.001407
    
    TTJets_HT-800to1200:
        names:
            - "TTJets_HT-800to1200_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-27_15-18-18"
        weights:
            - 1.0
    
    TTJets_HT-1200to2500:
        names:
            - "TTJets_HT-1200to2500_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-27_15-19-37"
        weights:
            - 1.0
    
    #ZprimeToTT_M1000_W10:
    #    names:
    #        - "ZprimeToTT_M1000_W10_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-20_16-43-00"
    #    weights:
    #        - 1.0
    
    ZprimeToTT_M2000_W20:
        names:
            - "ZprimeToTT_M2000_W20_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-27_15-35-11"
        weights:
            - 1.0
    
    #ZprimeToTT_M3000_W30:
    #    names:
    #        - "ZprimeToTT_M3000_W30_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-20_16-43-36"
    #    weights:
    #        - 1.0
    #
    #ZprimeToTT_M4000_W40:
    #    names:
    #        - "ZprimeToTT_M4000_W40_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-20_16-43-51"
    #    weights:
    #        - 1.0
    
    
    
    Wprimetotb_M3000W30:
        names:
            - "Wprimetotb_M3000W30_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2_MINIAODSIM:2022-04-28_18-03-46"
            - "Wprimetotb_M3000W30_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-28_18-03-54"
        weights:
            - 1.0
            - 1.0
    
    Wprimetotb_M4000W40:
        names:
            - "Wprimetotb_M4000W40_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-28_18-06-03"
            - "Wprimetotb_M4000W40_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-28_18-06-08"
        weights:
            - 1.0
            - 1.0
    
    Wprimetotb_M6000W60:
        names:
            - "Wprimetotb_M6000W60_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-28_18-11-35"
            - "Wprimetotb_M6000W60_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-28_18-11-40"
        weights:
            - 1.0
            - 1.0
    
    QCD:
        names:
            - "QCD_Pt_300to470_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-27_15-26-42"
            - "QCD_Pt_470to600_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2022-04-27_15-26-45"
            - "QCD_Pt_600to800_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-27_15-26-54"
            - "QCD_Pt_800to1000_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2022-04-27_15-26-57"
            - "QCD_Pt_1000to1400_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-27_15-27-03"
            - "QCD_Pt_1400to1800_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2022-04-27_15-27-09"
            - "QCD_Pt_1800to2400_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2022-04-27_15-27-13"
            - "QCD_Pt_2400to3200_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2022-04-27_15-27-28"
        weights:
            - 6826.0
            - 552.6
            - 156.6
            - 26.32
            - 7.5
            - 0.6479
            - 0.08715
            - 0.005242

#friendlist:
#    
#    pnet:
#        - 

curves:
    -   label: "t^{lep} (t#bar{t}: 800<H_{T}<1200 GeV) vs. QCD"
        sig:
            sample:         "TTJets_HT-800to1200"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        bkg:
            sample:         "QCD"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco > 1)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_with-WZ_2022-04-29_19-30-53"
                tag:                null
                #usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:        "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
        classifier:     "epoch9_lepTop_vs_qcd"
        classifiercut:  "{classifier} > {value}"
        color: 4
        linestyle: 1
    
    -   label: "t^{lep} (t#bar{t}: 1200<H_{T}<2500 GeV) vs. QCD"
        sig:
            sample:         "TTJets_HT-1200to2500"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        bkg:
            sample:         "QCD"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco > 1)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_with-WZ_2022-04-29_19-30-53"
                tag:                null
                #usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:        "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
        classifier:     "epoch9_lepTop_vs_qcd"
        classifiercut:  "{classifier} > {value}"
        color: 8
        linestyle: 1
    
    -   label: "t^{lep} (Z'_{2 TeV}) vs. QCD"
        sig:
            sample:         "ZprimeToTT_M2000_W20"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        bkg:
            sample:         "QCD"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco > 1)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_with-WZ_2022-04-29_19-30-53"
                tag:                null
                #usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:        "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
        classifier:     "epoch9_lepTop_vs_qcd"
        classifiercut:  "{classifier} > {value}"
        color: 2
        linestyle: 1
    
    #-   label: "t^{lep} (Z'_{4 TeV}) vs. QCD"
    #    sig:
    #        sample:         "ZprimeToTT_M4000_W40"
    #        tree:           "treeMaker/tree"
    #        source:         "ntupleLists/{sample}_{tag}.txt"
    #        weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
    #    bkg:
    #        sample:         "QCD"
    #        tree:           "treeMaker/tree"
    #        source:         "ntupleLists/{sample}_{tag}.txt"
    #        weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco > 1)"
    #    friends:
    #        -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_with-WZ_2022-04-29_19-30-53"
    #            tag:                null
    #            usefriendlist:      "pnet"
    #            tree:               "tree"
    #    vardict:
    #        jet:        "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
    #    classifier:     "epoch9_lepTop_vs_qcd"
    #    classifiercut:  "{classifier} > {value}"
    #    color: 6
    #    linestyle: 1
    
    -   label: "t^{lep} (W'_{4 TeV}) vs. QCD"
        sig:
            sample:         "Wprimetotb_M4000W40"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        bkg:
            sample:         "QCD"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco > 1)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_with-WZ_2022-04-29_19-30-53"
                tag:                null
                #usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:        "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
        classifier:     "epoch9_lepTop_vs_qcd"
        classifiercut:  "{classifier} > {value}"
        color: 7
        linestyle: 1
    
    -   label: "t^{lep} (W'_{6 TeV}) vs. QCD"
        sig:
            sample:         "Wprimetotb_M6000W60"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        bkg:
            sample:         "QCD"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco > 1)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_with-WZ_2022-04-29_19-30-53"
                tag:                null
                #usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:        "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
        classifier:     "epoch9_lepTop_vs_qcd"
        classifiercut:  "{classifier} > {value}"
        color: 9
        linestyle: 1

xtitle: "Signal efficiency"
ytitle: "Background efficiency"
xrange:
    - 0.0
    - 1.0
yrange:
    - 1.0e-6
    - 1.0
logx: false
logy: true
gridx: true
gridy: true
legendpos: "UL"
legendtextsize: 0.04
cpufrac: 0.9
outtag: "top-el-mu_vs_QCD"
#outfile: "plots/ROCs/particle_net_mod1b_ak8_with-WZ_2022-04-29_19-30-53/ROC.pdf"
outdir: "plots/ROCs/particle_net_mod1b_ak8_with-WZ_2022-04-29_19-30-53/2018"
