
samples:
    
    TTJets_HT-800to1200:
        names:
            - "TTJets_HT-800to1200_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-20_17-11-34"
        weights:
            - 1.0
    
    TTJets_HT-1200to2500:
        names:
            - "TTJets_HT-1200to2500_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-20_17-13-07"
        weights:
            - 1.0
    
    ZprimeToTT_M1000_W10:
        names:
            - "ZprimeToTT_M1000_W10_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-20_16-43-00"
        weights:
            - 1.0
    
    ZprimeToTT_M2000_W20:
        names:
            - "ZprimeToTT_M2000_W20_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-20_16-43-26"
        weights:
            - 1.0
    
    ZprimeToTT_M3000_W30:
        names:
            - "ZprimeToTT_M3000_W30_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-20_16-43-36"
        weights:
            - 1.0
    
    ZprimeToTT_M4000_W40:
        names:
            - "ZprimeToTT_M4000_W40_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-20_16-43-51"
        weights:
            - 1.0
    
    Wprimetotb_M4000W40:
        names:
            - "Wprimetotb_M4000W40_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-20_15-58-15"
            - "Wprimetotb_M4000W40_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-20_15-58-19"
        weights:
            - 1.0
            - 1.0
    
    Wprimetotb_M6000W60:
        names:
            - "Wprimetotb_M6000W60_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-20_16-02-21"
            - "Wprimetotb_M6000W60_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-20_16-02-26"
        weights:
            - 1.0
            - 1.0
    
    QCD:
        names:
            #- "QCD_Pt_170to300_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-06_01-19-55"
            - "QCD_Pt_300to470_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-06_01-19-59"
            - "QCD_Pt_470to600_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2022-04-06_01-20-03"
            - "QCD_Pt_600to800_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-06_01-20-11"
            - "QCD_Pt_800to1000_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2022-04-06_01-20-25"
            - "QCD_Pt_1000to1400_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-06_01-20-32"
            - "QCD_Pt_1400to1800_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2022-04-06_01-20-40"
            - "QCD_Pt_1800to2400_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2022-04-06_01-20-47"
            - "QCD_Pt_2400to3200_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2022-04-06_01-21-15"
        weights:
            #- 103300.0
            - 6826.0
            - 552.6
            - 156.6
            - 26.32
            - 7.5
            - 0.6479
            - 0.08715
            - 0.005242

friendlist:
    
    pnet:
        - "TTJets_HT-800to1200_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-06_02-30-09"
        - "TTJets_HT-1200to2500_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-06_02-31-42"
        
        - "ZprimeToTT_M1000_W10_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-05_15-51-22"
        - "ZprimeToTT_M2000_W20_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-05_15-51-53"
        - "ZprimeToTT_M3000_W30_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-05_15-52-02"
        - "ZprimeToTT_M4000_W40_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-05_15-52-21"
        
        - "Wprimetotb_M4000W40_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-05_15-54-46"
        - "Wprimetotb_M4000W40_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-05_15-54-50"
        
        - "Wprimetotb_M6000W60_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-05_15-59-46"
        - "Wprimetotb_M6000W60_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-05_15-59-51"
        
        #- "QCD_Pt_170to300_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-06_01-19-55"
        - "QCD_Pt_300to470_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-06_01-19-59"
        - "QCD_Pt_470to600_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2022-04-06_01-20-03"
        - "QCD_Pt_600to800_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-06_01-20-11"
        - "QCD_Pt_800to1000_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2022-04-06_01-20-25"
        - "QCD_Pt_1000to1400_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2022-04-06_01-20-32"
        - "QCD_Pt_1400to1800_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2022-04-06_01-20-40"
        - "QCD_Pt_1800to2400_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2022-04-06_01-20-47"
        - "QCD_Pt_2400to3200_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2022-04-06_01-21-15"

curves:
    -   label: "t^{lep} (t#bar{t}: 800<H_{T}<1200 GeV) vs. QCD"
        sig:
            sample:         "TTJets_HT-800to1200"
            tree:           "treeMaker/tree"
            source:         "sourceFiles/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 3) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        bkg:
            sample:         "QCD"
            tree:           "treeMaker/tree"
            source:         "sourceFiles/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 3) && ({jet}_nearestGenTopDR_reco > 1)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_2022-04-09_16-24-46"
                tag:                null
                usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:        "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
        classifier:     "epoch12_ltop_vs_qcd"
        classifiercut:  "{classifier} > {value}"
        color: 4
        linestyle: 1
    
    -   label: "t^{lep} (t#bar{t}: 1200<H_{T}<2500 GeV) vs. QCD"
        sig:
            sample:         "TTJets_HT-1200to2500"
            tree:           "treeMaker/tree"
            source:         "sourceFiles/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 3) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        bkg:
            sample:         "QCD"
            tree:           "treeMaker/tree"
            source:         "sourceFiles/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 3) && ({jet}_nearestGenTopDR_reco > 1)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_2022-04-09_16-24-46"
                tag:                null
                usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:        "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
        classifier:     "epoch12_ltop_vs_qcd"
        classifiercut:  "{classifier} > {value}"
        color: 8
        linestyle: 1
    
    -   label: "t^{lep} (Z'_{2 TeV}) vs. QCD"
        sig:
            sample:         "ZprimeToTT_M2000_W20"
            tree:           "treeMaker/tree"
            source:         "sourceFiles/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 3) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        bkg:
            sample:         "QCD"
            tree:           "treeMaker/tree"
            source:         "sourceFiles/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 3) && ({jet}_nearestGenTopDR_reco > 1)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_2022-04-09_16-24-46"
                tag:                null
                usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:        "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
        classifier:     "epoch12_ltop_vs_qcd"
        classifiercut:  "{classifier} > {value}"
        color: 2
        linestyle: 1
    
    -   label: "t^{lep} (Z'_{4 TeV}) vs. QCD"
        sig:
            sample:         "ZprimeToTT_M4000_W40"
            tree:           "treeMaker/tree"
            source:         "sourceFiles/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 3) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        bkg:
            sample:         "QCD"
            tree:           "treeMaker/tree"
            source:         "sourceFiles/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 3) && ({jet}_nearestGenTopDR_reco > 1)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_2022-04-09_16-24-46"
                tag:                null
                usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:        "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
        classifier:     "epoch12_ltop_vs_qcd"
        classifiercut:  "{classifier} > {value}"
        color: 6
        linestyle: 1
    
    -   label: "t^{lep} (W'_{4 TeV}) vs. QCD"
        sig:
            sample:         "Wprimetotb_M4000W40"
            tree:           "treeMaker/tree"
            source:         "sourceFiles/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 3) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        bkg:
            sample:         "QCD"
            tree:           "treeMaker/tree"
            source:         "sourceFiles/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 3) && ({jet}_nearestGenTopDR_reco > 1)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_2022-04-09_16-24-46"
                tag:                null
                usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:        "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
        classifier:     "epoch12_ltop_vs_qcd"
        classifiercut:  "{classifier} > {value}"
        color: 7
        linestyle: 1
    
    -   label: "t^{lep} (W'_{6 TeV}) vs. QCD"
        sig:
            sample:         "Wprimetotb_M6000W60"
            tree:           "treeMaker/tree"
            source:         "sourceFiles/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 3) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        bkg:
            sample:         "QCD"
            tree:           "treeMaker/tree"
            source:         "sourceFiles/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 3) && ({jet}_nearestGenTopDR_reco > 1)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_2022-04-09_16-24-46"
                tag:                null
                usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:        "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
        classifier:     "epoch12_ltop_vs_qcd"
        classifiercut:  "{classifier} > {value}"
        color: 9
        linestyle: 1

xtitle: "Signal efficiency"
ytitle: "Background efficiency"
xrange:
    - 0.0
    - 1.0
yrange:
    - 1.0e-6
    - 1.0
logx: false
logy: true
gridx: true
gridy: true
legendpos: "UL"
legendtextsize: 0.04
cpufrac: 0.9
outtag: "top-el-mu"
#outfile: "plots/ROCs/particle_net_mod1b_ak8_2022-04-09_16-24-46/ROC.pdf"
outdir: "plots/ROCs/particle_net_mod1b_ak8_2022-04-09_16-24-46/2018"
