
samples:
    
    TTJets:
        names:
            - "TTJets_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
            - "TTJets_HT-800to1200_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
            - "TTJets_HT-1200to2500_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
            - "TTJets_HT-2500toInf_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
        weights:
            - 1.821
            - 0.7532
            - 0.1316
            - 0.001407
    
    TTJets_HT-800to1200:
        names:
            - "TTJets_HT-800to1200_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
        weights:
            - 1.0
    
    TTJets_HT-1200to2500:
        names:
            - "TTJets_HT-1200to2500_TuneCP5_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
        weights:
            - 1.0
    
    #ZprimeToTT_M1000_W10:
    #    names:
    #        - "ZprimeToTT_M1000_W10_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
    #    weights:
    #        - 1.0
    
    ZprimeToTT_M2000_W20:
        names:
            - "ZprimeToTT_M2000_W20_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
        weights:
            - 1.0
    
    #ZprimeToTT_M3000_W30:
    #    names:
    #        - "ZprimeToTT_M3000_W30_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
    #    weights:
    #        - 1.0
    #
    #ZprimeToTT_M4000_W40:
    #    names:
    #        - "ZprimeToTT_M4000_W40_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
    #    weights:
    #        - 1.0
    
    
    
    Wprimetotb_M3000W30:
        names:
            - "Wprimetotb_M3000W30_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2_MINIAODSIM:latest"
            - "Wprimetotb_M3000W30_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
        weights:
            - 1.0
            - 1.0
    
    Wprimetotb_M4000W40:
        names:
            - "Wprimetotb_M4000W40_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
            - "Wprimetotb_M4000W40_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
        weights:
            - 1.0
            - 1.0
    
    Wprimetotb_M6000W60:
        names:
            - "Wprimetotb_M6000W60_LH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
            - "Wprimetotb_M6000W60_RH_TuneCP5_13TeV-madgraph-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
        weights:
            - 1.0
            - 1.0
    
    QCD:
        names:
            - "QCD_Pt_300to470_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
            - "QCD_Pt_470to600_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:latest"
            - "QCD_Pt_600to800_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
            - "QCD_Pt_800to1000_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:latest"
            - "QCD_Pt_1000to1400_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM:latest"
            - "QCD_Pt_1400to1800_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:latest"
            - "QCD_Pt_1800to2400_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:latest"
            - "QCD_Pt_2400to3200_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:latest"
        weights:
            - 6826.0
            - 552.6
            - 156.6
            - 26.32
            - 7.5
            - 0.6479
            - 0.08715
            - 0.005242
    

#friendlist:
#    
#    pnet:
#        - 

curves:
    
    -   label: "AK8 t^{lep} jets [W'_{6 TeV}#; w.r.t. gen#; logit(o) > 5]"
        num:
            sample:         "Wprimetotb_M6000W60"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            plot:           "genTop_pT[{jet}_nearestGenTopIdx_reco]"
            weight:         "({classifier} > 5) && ({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        den:
            sample:         "Wprimetotb_M6000W60"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            plot:           "genTop_pT"
            weight:         "(genTop_pT > 0) && (abs(genTop_eta) < 2.5) && (abs(genTop_isLeptonic) > 0.5)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_with-WZ_2022-05-11_18-55-28"
                tag:                null
                #usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:            "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
            classifier:     "log(max(1e-32, epoch11_lepTop_vs_qcd)/max(1.0e-32, 1.0-epoch11_lepTop_vs_qcd))"
        color: 2
        linestyle: 1
    
    
    -   label: "AK8 t^{lep} jets [W'_{6 TeV}#; w.r.t. reco#; logit(o) > 5]"
        num:
            sample:         "Wprimetotb_M6000W60"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            plot:           "genTop_pT[{jet}_nearestGenTopIdx_reco]"
            weight:         "({classifier} > 5) && ({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        den:
            sample:         "Wprimetotb_M6000W60"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            plot:           "genTop_pT[{jet}_nearestGenTopIdx_reco]"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_with-WZ_2022-05-11_18-55-28"
                tag:                null
                #usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:            "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
            classifier:     "log(max(1e-32, epoch11_lepTop_vs_qcd)/max(1.0e-32, 1.0-epoch11_lepTop_vs_qcd))"
        color: 2
        linestyle: 2
    
    
    -   label: "AK8 t^{lep} jets [W'_{6 TeV}#; w.r.t. gen#; logit(o) > 10]"
        num:
            sample:         "Wprimetotb_M6000W60"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            plot:           "genTop_pT[{jet}_nearestGenTopIdx_reco]"
            weight:         "({classifier} > 10) && ({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        den:
            sample:         "Wprimetotb_M6000W60"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            plot:           "genTop_pT"
            weight:         "(genTop_pT > 0) && (abs(genTop_eta) < 2.5) && (abs(genTop_isLeptonic) > 0.5)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_with-WZ_2022-05-11_18-55-28"
                tag:                null
                #usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:            "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
            classifier:     "log(max(1e-32, epoch11_lepTop_vs_qcd)/max(1.0e-32, 1.0-epoch11_lepTop_vs_qcd))"
        color: 4
        linestyle: 1
    
    
    -   label: "AK8 t^{lep} jets [W'_{6 TeV}#; w.r.t. reco#; logit(o) > 10]"
        num:
            sample:         "Wprimetotb_M6000W60"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            plot:           "genTop_pT[{jet}_nearestGenTopIdx_reco]"
            weight:         "({classifier} > 10) && ({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        den:
            sample:         "Wprimetotb_M6000W60"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            plot:           "genTop_pT[{jet}_nearestGenTopIdx_reco]"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_with-WZ_2022-05-11_18-55-28"
                tag:                null
                #usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:            "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
            classifier:     "log(max(1e-32, epoch11_lepTop_vs_qcd)/max(1.0e-32, 1.0-epoch11_lepTop_vs_qcd))"
        color: 4
        linestyle: 2
    
    
    -   label: "AK8 t^{lep} jets [W'_{6 TeV}#; w.r.t. gen#; logit(o) > 15]"
        num:
            sample:         "Wprimetotb_M6000W60"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            plot:           "genTop_pT[{jet}_nearestGenTopIdx_reco]"
            weight:         "({classifier} > 15) && ({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        den:
            sample:         "Wprimetotb_M6000W60"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            plot:           "genTop_pT"
            weight:         "(genTop_pT > 0) && (abs(genTop_eta) < 2.5) && (abs(genTop_isLeptonic) > 0.5)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_with-WZ_2022-05-11_18-55-28"
                tag:                null
                #usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:            "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
            classifier:     "log(max(1e-32, epoch11_lepTop_vs_qcd)/max(1.0e-32, 1.0-epoch11_lepTop_vs_qcd))"
        color: 6
        linestyle: 1
    
    
    -   label: "AK8 t^{lep} jets [W'_{6 TeV}#; w.r.t. reco#; logit(o) > 15]"
        num:
            sample:         "Wprimetotb_M6000W60"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            plot:           "genTop_pT[{jet}_nearestGenTopIdx_reco]"
            weight:         "({classifier} > 15) && ({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        den:
            sample:         "Wprimetotb_M6000W60"
            tree:           "treeMaker/tree"
            source:         "ntupleLists/{sample}_{tag}.txt"
            plot:           "genTop_pT[{jet}_nearestGenTopIdx_reco]"
            weight:         "({jet}_pT_reco > 400) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 1) && ({jet}_nearestGenTopDR_reco < 0.6) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5) && ({jet}_nearestGenTopbDR_reco < 0.6) && ({jet}_nearestGenTopWlepDR_reco < 0.6)"
        friends:
            -   dir:                "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/particle_net_mod1b_ak8_with-WZ_2022-05-11_18-55-28"
                tag:                null
                #usefriendlist:      "pnet"
                tree:               "tree"
        vardict:
            jet:            "jet_selectedPatJetsAK8PFPuppi_boost_2_1_sd_z0p1_b0_R1"
            classifier:     "log(max(1e-32, epoch11_lepTop_vs_qcd)/max(1.0e-32, 1.0-epoch11_lepTop_vs_qcd))"
        color: 6
        linestyle: 2

#bins: "numpy.concatenate([numpy.arange(0.0, 1500.0, 100), numpy.arange(1500.0, 2500.0, 500), numpy.array([3000, 5000])], axis = None)"
#bins: "numpy.concatenate([numpy.arange(0.0, 2000.0, 100), numpy.arange(2000.0, 10000.0, 500)], axis = None)"
bins: "numpy.concatenate([numpy.arange(0.0, 2000.0, 200), numpy.arange(2000.0, 3000.0, 500), numpy.arange(3000.0, 10000.0, 1000)], axis = None)"
#bins: "numpy.concatenate([numpy.arange(0.0, 10000.0, 100)], axis = None)"

xtitle: "t^{lep}_{gen} p_{T} [GeV]"
ytitle: "Efficiency"
xrange:
    - 0.0
    - 5000.0
yrange:
    - 0.0
    - 2.0
logx: false
logy: false
gridx: true
gridy: true
legendpos: "UL"
legendncol: 1
legendtextsize: 0.03
cpufrac: 0.9
outname: "lepTop-efficiency_vs_genTop-pT_eval-WprimetotbM6000W60"
outtag: "classifier-lepTop-vs-QCD"
outdir: "plots/efficiencies/particle_net_mod1b_ak8_with-WZ_2022-05-11_18-55-28/2018"
